" ============================================
" MY VERY .VIMRC!!!
" ============================================

" --------------------------------------------
" 1. IMPORTANT
" --------------------------------------------
" Link to Vundle
so ~/dotfiles/vim/vundle.vim

" --------------------------------------------
" 2. MOVING AROUND, SEARCHING AND PATTERNS
" --------------------------------------------
" Automatically changes to dir of file in buffer
set autochdir
" Shows search match as you type
set incsearch
" Ignores case when using a search pattern
set ignorecase
" Overrides 'ignorecase' when pattern has upper chars
set smartcase

" --------------------------------------------
" 3. TAGS
" --------------------------------------------

" --------------------------------------------
" 4. DISPLAYING TEXT
" --------------------------------------------
" Displays line number
set number
" Number of lines for the command window
set cmdheight=2
" Change default fonts
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 10
" Wrap longlines at space ' '
"set linebreak
" Don't wrap long lines
set nowrap
" Make sure there are at least 3 lines under the cursor
set scrolloff=3
" Make whitespaces visible
set list
" and the listchars
" reset it first
set listchars=""
" a tab should display as `,
set listchars=tab:>-
" trailing whitespace as .
set listchars+=trail:.
" Show < or > when characters are not displayed on the left or right.
set listchars+=extends:>
set listchars+=precedes:<

" --------------------------------------------
" 5. SYNTAX, HIGHLIGHTING and SPELLING
" --------------------------------------------
" Enables syntax highlighting
syntax enable
" Filetype Detection ON
filetype plugin indent on
" 80-character indicator line
set colorcolumn=80
" Highlight all matches search result
set hlsearch

" --------------------------------------------
" 6 MULTIPLE WINDOWS
" --------------------------------------------
set laststatus=2

" --------------------------------------------
" 7 MULTIPLE TAB PAGES
" --------------------------------------------

" --------------------------------------------
" 8 TERMINAL
" --------------------------------------------
set ttyfast

" --------------------------------------------
" 9 USING THE MOUSE
" --------------------------------------------

" --------------------------------------------
" 10 GUI
" --------------------------------------------

" --------------------------------------------
" 11 PRINTING
" --------------------------------------------

" --------------------------------------------
" 12 MESSAGES AND INFO
" --------------------------------------------
" Shows incomplete commands as type
set showcmd
" Display the current mode in the status bar
set showmode
" Always displays the current cursor position in Status Bar
set ruler
" Asks to save buffer instead of failing when executing
" commands which close buffers
set confirm
" Well, a nice bell
set visualbell

" --------------------------------------------
" 13 SELECTING TEXT
" --------------------------------------------

" --------------------------------------------
" 14 EDITING TEXT
" --------------------------------------------
" Allows backspacing over everything
set backspace=indent,eol,start
" Shows matching parenthesis
set showmatch
" Uses many levels of undo
set undolevels=1000
" Use omnifunc for css
set omnifunc=csscomplete#CompleteCSS


" --------------------------------------------
" 15 TABS AND INDENTING
" I prefer <space> to <tab>
" --------------------------------------------
" Auto indenting ON
set autoindent
" Copies the previous indentation on auto indenting
set copyindent
" Uses spaces instead of tabs
set expandtab
" Sets tab stop = 4 - my fav stop
set tabstop=4
" Number of spaces used for auto indenting
set shiftwidth=4
" Inserts tabs on the start of a line according to shiftwidth
set smarttab
" Uses multiple of shiftwidth when indenting with '<' and '>'
set shiftround

" --------------------------------------------
" 16 FOLDING
" --------------------------------------------

" --------------------------------------------
" 17 DIFF MODE
" --------------------------------------------

" --------------------------------------------
" 18 MAPPING
" --------------------------------------------

" --------------------------------------------
" 19 READING AND WRITING FILES
" --------------------------------------------
" Auto reloads file on change
set autoread
" Prevent some security exploits having to do with modelines
set modelines=0

" --------------------------------------------
" 20 THE SWAP FILE
" --------------------------------------------


" --------------------------------------------
" 21 COMMAND LINE EDITING
" --------------------------------------------
" Remembers 500 commands
set history=500
" Command-line completion shows a list of matches
set wildmenu
set wildmode=list:longest,full

" --------------------------------------------
" 22 EXECUTING EXTERNAL COMMANDS
" --------------------------------------------

" --------------------------------------------
" 23 RUNNING MAKE AND JUMPING TO ERRORS
" --------------------------------------------

" --------------------------------------------
" 24 LANGUAGE SPECIFIC
" --------------------------------------------

" --------------------------------------------
" 25 MULTI-BYTE CHARACTERS
" --------------------------------------------
" Changes encoding to UTF-8
set encoding=utf-8

" --------------------------------------------
" 26 VARIOUS
" --------------------------------------------

" --------------------------------------------
" FUNCTIONS
" --------------------------------------------
so ~/dotfiles/vim/functions.vim

" --------------------------------------------
" CUSTOM KEY BINDINGS
" --------------------------------------------
so ~/dotfiles/vim/shortcut.vim

" ============================================
" END MY VERY .VIMRC!!!
" ============================================
