" ============================================
" MY VERY .VIMRC!!!
" ============================================

" --------------------------------------------
" 1. IMPORTANT
" --------------------------------------------
" Link to Vundle
so ~/dotfiles/vim/vundle.vim

" --------------------------------------------
" 2. MOVING AROUND, SEARCHING AND PATTERNS
" --------------------------------------------
" Automatically changes to dir of file in buffer
set autochdir
" Shows search match as you type
set incsearch
" Ignores case when using a search pattern
set ignorecase
" Overrides 'ignorecase' when pattern has upper chars
set smartcase

" --------------------------------------------
" 3. TAGS
" --------------------------------------------

" --------------------------------------------
" 4. DISPLAYING TEXT
" --------------------------------------------
" Displays line number
set number
" Number of lines for the command window
set cmdheight=2
" Change default fonts
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 10
" Wrap longlines at space ' '
set linebreak
" Make sure there are at least 3 lines under the cursor
set scrolloff=3

" --------------------------------------------
" 5. SYNTAX, HIGHLIGHTING and SPELLING
" --------------------------------------------
" Enables syntax highlighting
syntax enable
" Filetype Detection ON
filetype plugin indent on
" 80-character indicator line
set colorcolumn=80
" Highlight all matches search result
set hlsearch

" --------------------------------------------
" 6 MULTIPLE WINDOWS
" --------------------------------------------
set laststatus=2

" --------------------------------------------
" 7 MULTIPLE TAB PAGES
" --------------------------------------------

" --------------------------------------------
" 8 TERMINAL
" --------------------------------------------
set ttyfast

" --------------------------------------------
" 9 USING THE MOUSE
" --------------------------------------------

" --------------------------------------------
" 10 GUI
" --------------------------------------------

" --------------------------------------------
" 11 PRINTING
" --------------------------------------------

" --------------------------------------------
" 12 MESSAGES AND INFO
" --------------------------------------------
" Shows incomplete commands as type
set showcmd
" Display the current mode in the status bar
set showmode
" Always displays the current cursor position in Status Bar
set ruler
" Asks to save buffer instead of failing when executing
" commands which close buffers
set confirm
" Well, a nice bell
set visualbell

" --------------------------------------------
" 13 SELECTING TEXT
" --------------------------------------------

" --------------------------------------------
" 14 EDITING TEXT
" --------------------------------------------
" Allows backspacing over everything
set backspace=indent,eol,start
" Shows matching parenthesis
set showmatch
" Uses many levels of undo
set undolevels=1000
" Use omnifunc for css
set omnifunc=csscomplete#CompleteCSS


" --------------------------------------------
" 15 TABS AND INDENTING
" I prefer <space> to <tab>
" --------------------------------------------
" Auto indenting ON
set autoindent
" Copies the previous indentation on auto indenting
set copyindent
" Uses spaces instead of tabs
set expandtab
" Sets tab stop = 4 - my fav stop
set tabstop=4
" Number of spaces used for auto indenting
set shiftwidth=4
" Inserts tabs on the start of a line according to shiftwidth
set smarttab
" Uses multiple of shiftwidth when indenting with '<' and '>'
set shiftround

" --------------------------------------------
" 16 FOLDING
" --------------------------------------------

" --------------------------------------------
" 17 DIFF MODE
" --------------------------------------------

" --------------------------------------------
" 18 MAPPING
" --------------------------------------------

" --------------------------------------------
" 19 READING AND WRITING FILES
" --------------------------------------------
" Auto reloads file on change
set autoread
" Prevent some security exploits having to do with modelines
set modelines=0

" --------------------------------------------
" 20 THE SWAP FILE
" --------------------------------------------


" --------------------------------------------
" 21 COMMAND LINE EDITING
" --------------------------------------------
" Remembers 500 commands
set history=500
" Command-line completion shows a list of matches
set wildmenu
set wildmode=list:longest,full 

" --------------------------------------------
" 22 EXECUTING EXTERNAL COMMANDS
" --------------------------------------------

" --------------------------------------------
" 23 RUNNING MAKE AND JUMPING TO ERRORS
" --------------------------------------------

" --------------------------------------------
" 24 LANGUAGE SPECIFIC
" --------------------------------------------

" --------------------------------------------
" 25 MULTI-BYTE CHARACTERS
" --------------------------------------------
" Changes encoding to UTF-8
set encoding=utf-8

" --------------------------------------------
" 26 VARIOUS
" --------------------------------------------

" --------------------------------------------
" FUNCTIONS
" --------------------------------------------
" Auto reloads vimrc
augroup myvimrchooks
	au!
	autocmd bufwritepost .vimrc source ~/.vimrc
augroup END

" Visually selects text and press ~ to toggle through cases.
" There are three types:
" 	all lowercase,
" 	ALL UPPERCASE,
" 	First Letter Uppercase
" ToggleCase(str) {
function! ToggleCase(str)
	if a:str ==# toupper(a:str)
		let result = tolower(a:str)
	elseif a:str ==# tolower(a:str)
		let result = substitute(a:str,'\(\<\w\+\>\)', '\u\1', 'g')
	else
		let result = toupper(a:str)
	endif
	return result
endfunction
" map '~' to ToggleCase()
vnoremap ~ ygv"=ToggleCase(@")<CR>Pgv
" }

" Indent options for Ruby group
function SetRubyAndWebOption()
    setlocal shiftwidth=2
    setlocal tabstop=2
endfunction
autocmd Filetype ruby call SetRubyAndWebOption()
autocmd Filetype eruby call SetRubyAndWebOption()
autocmd Filetype html call SetRubyAndWebOption()
autocmd Filetype haml call SetRubyAndWebOption()
autocmd Filetype liquid call SetRubyAndWebOption()


" --------------------------------------------
" CUSTOM KEY BINDINGS
" --------------------------------------------

"  1 IMPORTANT -------------------------------
" Map 'jk' to <ESC>
inoremap jk <ESC>

" ';' could be used as ':'
nnoremap ; :
vnoremap ; :

" Maps <leader> from \ to ,
let mapleader=","

" C-w is super difficult to press, so make it <leader>w
nmap <leader>w <c-w>

"  2 MOVING AROUND, SEARCHING AND PATTERNS ---

"  3 TAGS ------------------------------------

"  4 DISPLAYING TEXT -------------------------

"  5 SYNTAX, HIGHLIGHTING AND SPELLING -------
" Clear out a search
nnoremap <leader><space> :noh<cr>

"  6 MULTIPLE WINDOWS ------------------------
" Moving around splits using Ctrl+h/j/k/l
map <c-j> <c-w>j
map <c-h> <c-w>h
map <c-k> <c-w>k
map <c-l> <c-w>l

" F11 maximizes current split (vertically only)
nnoremap <f11> <c-w>99+

" F12 minimizes current split (vertically only)
nnoremap <f12> <c-w>99-

" Up Down to adjust current split size
nnoremap <up> <c-w>+
nnoremap <down> <c-w>-

"  7 MULTIPLE TAB PAGES ----------------------
" Moving around tabs by <leader>n\m
nnoremap <leader>n <esc>:tabp<cr>
nnoremap <leader>m <esc>:tabn<cr>

"  8 TERMINAL --------------------------------

"  9 USING THE MOUSE -------------------------

" 10 GUI -------------------------------------

" 11 PRINTING --------------------------------

" 12 MESSAGES AND INFO -----------------------

" 13 SELECTING TEXT --------------------------

" 14 EDITING TEXT ----------------------------
" Auto add ; at the last
inoremap <leader>s <C-o>m`<C-o>A;<C-o>``

" Move lines
nmap <A-j> :m<space>.+1<CR>==
nmap <A-S-up> :m<space>.-2<CR>==
inoremap <A-S-down> <Esc>:m .+1<CR>==gi
inoremap <A-S-up> <Esc>:m .-2<CR>==gi
vnoremap <A-S-down> :m '>+1<CR>gv=gv
vnoremap <A-S-up> :m '<-2<CR>gv=gv

" 15 TABS AND INDENTING ----------------------
" F8 indents whole file
nnoremap <f8> gg=G
" Easier block indenting (does not exit visual mode after one shift)
vnoremap <S-Tab> <gv
vnoremap <Tab> >gv

" 16 FOLDING ---------------------------------

" 17 DIFF MODE -------------------------------

" 18 MAPPING ---------------------------------

" 19 READING AND WRITING FILES ---------------
" Write file with sudo permission
nnoremap <leader>wf :w<space>!sudo<space>tee<space>%<cr>

" Quickly open config files ----- {{{
" Vimrc files
nnoremap <leader>ve :e<space>~/.vimrc<cr>
nnoremap <leader>vt :tabe<space>~/.vimrc<cr> " Open in newtab
nnoremap <leader>vv :tabe<space>~/dotfiles/vim/vundle.vim<cr> "This one too
" Zshrc files
nnoremap <leader>zr :e<space>~/.zshrc<cr>
nnoremap <leader>zt :e<space>~/dotfiles/oh-my-zsh-custom/tklarry.zsh-theme<cr>
" Git config files
nnoremap <leader>gc :e<space>~/.gitconfig<cr>
nnoremap <leader>gt :tabe<space>~/.gitconfig<cr>
" }}}

" Left Right to cycle through buffers
nnoremap <left> <c-w><
nnoremap <right> <c-w>>

" Open vim options help file in new tab
nnoremap <leader>h :tabe<space>~/Documents/optionwindow<cr>

" 20 THE SWAP FILE ---------------------------

" 21 COMMAND LINE EDITING --------------------
" Make C-space usable
imap <Nul> <C-Space>

" 22 EXECUTING EXTERNAL COMMANDS/PLUGINS -----
" NERDTree
nnoremap <leader>d <esc>:NERDTree<cr>
nnoremap <leader>e :NERDTreeToggle<cr>

" F5 toggles tagbar
nnoremap <f5> :TagbarToggle<cr>

" F6 Compile the file
nnoremap <F6> <esc>:SCCompile<CR>

" Ctrl + F6 compile and run
nnoremap <C-F6> <esc>:SCCompileRun<CR>

" 23 RUNNING MAKE AND JUMPING TO ERRORS ------

" 24 LANGUAGE SPECIFIC -----------------------

" 25 MULTI-BYTE CHARACTERS -------------------

" 26 VARIOUS ---------------------------------

" ============================================
" END MY VERY .VIMRC!!!
" ============================================
